name: happy_hour_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.16.0 <3.2.0"


dependency_overrides:
  firebase_core_platform_interface: 4.5.1
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: any
  get: any
  intl: any
  responsive_framework: any
  font_awesome_flutter: any
  flutter_svg: any
  toggle_switch: any
  google_maps_flutter: any
  flutter_credit_card: any
  carousel_pro:
  card_swiper: any
  get_storage: any
  image_picker: any
  flutter_rating_bar: any
  firebase_core: ^1.20.0
  cloud_firestore: any
  firebase_storage: any
#  fluttertoast: ^8.1.3
  firebase_auth: any
  flutterfire_ui: any
  cached_network_image: any
  location: any

  url_launcher: any
  multiselect: any
  geolocator: any
  geocoding: any
  photo_view: any
  flutter_typeahead: any
  geoflutterfire: any
  dio: any
  google_maps_place_picker_mb: any
  multi_select_flutter: ^4.1.2
  photo_gallery: any
  flutter_spinkit: any
  connectivity: any
  # flutter_stripe: ^2.1.0
  flutter_config: any
  cloud_functions: any
  permission_handler: any
  lottie: any
  pinch_zoom: any
  syncfusion_flutter_sliders: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env
  #   - images/a_dot_ham.jpeg

