// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA00OIomwYPis252cTpeS7mO_Ocy7wHVC4',
    appId: '1:74293911007:web:cb431f130fce84a157f86a',
    messagingSenderId: '74293911007',
    projectId: 'happyhours-c15a8',
    authDomain: 'happyhours-c15a8.firebaseapp.com',
    storageBucket: 'happyhours-c15a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUu6BNQKu6sVPKg492PuPCyWzbbUYo6NM',
    appId: '1:74293911007:android:6788e1bcb5c3c72b57f86a',
    messagingSenderId: '74293911007',
    projectId: 'happyhours-c15a8',
    storageBucket: 'happyhours-c15a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlp11ctZT0E18R5HLQuXclQ7gW9XMNkvc',
    appId: '1:74293911007:ios:990d6ab7e0ab746557f86a',
    messagingSenderId: '74293911007',
    projectId: 'happyhours-c15a8',
    storageBucket: 'happyhours-c15a8.appspot.com',
    iosClientId:
        '74293911007-8vnnu6jvk043p725mb0sq5mif29c9oo8.apps.googleusercontent.com',
    iosBundleId: 'com.esols.imrankhan.happyhour',
  );
}



// import 'package:flutter/material.dart';
// import 'package:flutter_svg/flutter_svg.dart';
// import 'package:get/get.dart';

// import '../../../../core/colors.dart';
// import '../../../../core/constants.dart';
// import '../../../../global_widgets/main_button.dart';
// import '../addhappyhour_business_controller.dart';

// class BusinessDayTimeScreen extends GetView<AddHappyhourBusinessController> {
//   const BusinessDayTimeScreen({Key? key}) : super(key: key);

//   @override
//   Widget build(BuildContext context) {
//     return GetBuilder<AddHappyhourBusinessController>(builder: (controller) {
//       return Scaffold(
//         backgroundColor: bgColor,
//         appBar: AppBar(
//           backgroundColor: Colors.transparent,
//           elevation: 0,
//           leading: IconButton(
//               onPressed: () {
//                 for (var e in controller.dayTimeList) {
//                   e.isSelect = false.obs;
//                 }
//                 Get.back();
//               },
//               icon: SvgPicture.asset(
//                 "assets/icons/Group 9108.svg",
//                 height: 25,
//                 width: 25,
//               )),
//           title: const Text("Add Happy Hour"),
//           centerTitle: true,
//         ),
//         body: SingleChildScrollView(
//           child: Form(
//             key: controller.businessKey,
//             child: Padding(
//               padding: const EdgeInsets.all(8),
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   SizedBox(
//                     height: H * 0.009,
//                   ),
//                   const Padding(
//                     padding: EdgeInsets.only(left: 8.0),
//                     child: Text(
//                       "Add Happy Hour Details",
//                       style: TextStyle(
//                         fontSize: 20,
//                         fontWeight: FontWeight.w700,
//                       ),
//                     ),
//                   ),
//                   SizedBox(
//                     height: H * 0.02,
//                   ),
//                   Padding(
//                     padding: EdgeInsets.only(left: W * 0.08, right: W * 0.14),
//                     child: Row(
//                       mainAxisAlignment: MainAxisAlignment.spaceBetween,
//                       children: const [
//                         SizedBox(
//                           width: 1,
//                         ),
//                         Text(
//                           "Day",
//                           style: TextStyle(
//                             fontSize: 18,
//                             color: blackColor,
//                             fontWeight: FontWeight.bold,
//                           ),
//                         ),
//                         Text(
//                           "From Time",
//                           style: TextStyle(
//                             fontSize: 18,
//                             color: blackColor,
//                             fontWeight: FontWeight.bold,
//                           ),
//                         ),
//                         Text(
//                           "To Time",
//                           style: TextStyle(
//                             fontSize: 18,
//                             color: blackColor,
//                             fontWeight: FontWeight.bold,
//                           ),
//                         ),
//                       ],
//                     ),
//                   ),
//                   SizedBox(
//                     height: H * 0.02,
//                   ),
//                   ListView.builder(
//                       shrinkWrap: true,
//                       itemCount: controller.dayTimeList.length,
//                       itemBuilder: (BuildContext context, int index) {
//                         return Padding(
//                           padding:
//                               EdgeInsets.only(left: W * 0.01, right: W * 0.06),
//                           child: Column(
//                             children: [
//                               Row(
//                                 mainAxisAlignment:
//                                     MainAxisAlignment.spaceBetween,
//                                 children: [
//                                   Transform.scale(
//                                     scale: 0.6,
//                                     child: Obx(
//                                       () => Card(
//                                         margin: const EdgeInsets.all(1),
//                                         elevation: 3,
//                                         shape: const StadiumBorder(),
//                                         child: Transform.scale(
//                                           scale: 2.0,
//                                           child: Checkbox(
//                                               checkColor: Colors.amber,
//                                               splashRadius: 20,
//                                               shape: const StadiumBorder(),
//                                               side: BorderSide.none,
//                                               value: controller
//                                                   .dayTimeList[index]
//                                                   .isSelect
//                                                   .value,
//                                               onChanged: (val) {
//                                                 controller.dayTimeList[index]
//                                                         .isSelect.value =
//                                                     !controller
//                                                         .dayTimeList[index]
//                                                         .isSelect
//                                                         .value;

//                                                 controller.hUpdateDay(index);
//                                                 if (controller
//                                                     .dayTimeList[index]
//                                                     .isSelect
//                                                     .isFalse) {
//                                                   controller
//                                                       .businessKey.currentState!
//                                                       .reset();
//                                                 }
//                                               }),
//                                         ),
//                                       ),
//                                     ),
//                                   ),
//                                   SizedBox(
//                                     width: W * 0.24,
//                                     child: Text(
//                                       controller.dayTimeList[index].day,
//                                       style: const TextStyle(fontSize: 16),
//                                     ),
//                                   ),
//                                   Obx(
//                                     () => Card(
//                                       shape: RoundedRectangleBorder(
//                                         borderRadius: BorderRadius.circular(45),
//                                       ),
//                                       elevation: 5,
//                                       child: SizedBox(
//                                         height: H * 0.04,
//                                         width: W * 0.26,
//                                         child: DropdownButtonFormField<String>(
//                                           validator: controller
//                                                   .dayTimeList[index]
//                                                   .isSelect
//                                                   .isTrue
//                                               ? (value) {
//                                                   if (value == null ||
//                                                       value.trim().isEmpty) {
//                                                     return 'select';
//                                                   }

//                                                   return null;
//                                                 }
//                                               : null,
//                                           elevation: 15,
//                                           decoration: const InputDecoration(
//                                             enabled: false,
//                                             contentPadding: EdgeInsets.fromLTRB(
//                                                 12.0, 2.0, 8.0, 2.0),
//                                             filled: true,
//                                             fillColor: Colors.white,
//                                             border: OutlineInputBorder(
//                                               borderRadius: BorderRadius.all(
//                                                   Radius.circular(45)),
//                                             ),
//                                           ),
//                                           isExpanded: true,
//                                           hint: const Text(
//                                             "Select Time",
//                                             style: TextStyle(
//                                                 fontSize: 12,
//                                                 color: Colors.grey),
//                                           ),
//                                           icon: const Icon(
//                                               Icons.keyboard_arrow_down),
//                                           items: controller.dayTimeList[index]
//                                                   .isSelect.isTrue
//                                               ? controller.timesList
//                                                   .map((time) =>
//                                                       DropdownMenuItem(
//                                                         value: time,
//                                                         child: Text(
//                                                           time,
//                                                           style:
//                                                               const TextStyle(
//                                                             color: Colors.black,
//                                                             fontSize: 12,
//                                                           ),
//                                                         ),
//                                                       ))
//                                                   .toList()
//                                               : [],
//                                           onChanged: (time) {
//                                             controller.dayTimeList[index]
//                                                 .fromTime = time!;
//                                           },
//                                         ),
//                                       ),
//                                     ),
//                                   ),
//                                   Obx(
//                                     () => Card(
//                                       shape: RoundedRectangleBorder(
//                                         borderRadius: BorderRadius.circular(45),
//                                       ),
//                                       elevation: 5,
//                                       child: SizedBox(
//                                         height: H * 0.04,
//                                         width: W * 0.26,
//                                         child: DropdownButtonFormField<String>(
//                                           validator: controller
//                                                   .dayTimeList[index]
//                                                   .isSelect
//                                                   .isTrue
//                                               ? (value) {
//                                                   if (value == null ||
//                                                       value.trim().isEmpty) {
//                                                     return 'select';
//                                                   }

//                                                   return null;
//                                                 }
//                                               : null,
//                                           elevation: 15,
//                                           decoration: const InputDecoration(
//                                             enabled: false,
//                                             contentPadding: EdgeInsets.fromLTRB(
//                                                 12.0, 2.0, 8.0, 2.0),
//                                             filled: true,
//                                             fillColor: Colors.white,
//                                             border: OutlineInputBorder(
//                                               borderRadius: BorderRadius.all(
//                                                   Radius.circular(45)),
//                                             ),
//                                           ),
//                                           isExpanded: true,
//                                           hint: const Text(
//                                             "Select Time",
//                                             style: TextStyle(
//                                                 fontSize: 12,
//                                                 color: Colors.grey),
//                                           ),
//                                           icon: const Icon(
//                                               Icons.keyboard_arrow_down),
//                                           items: controller.dayTimeList[index]
//                                                   .isSelect.isTrue
//                                               ? controller.timesList
//                                                   .map((time) =>
//                                                       DropdownMenuItem(
//                                                         value: time,
//                                                         child: Text(
//                                                           time,
//                                                           style:
//                                                               const TextStyle(
//                                                             color: Colors.black,
//                                                             fontSize: 12,
//                                                           ),
//                                                         ),
//                                                       ))
//                                                   .toList()
//                                               : [],
//                                           onChanged: (time) {
//                                             controller.dayTimeList[index]
//                                                 .toTime = time!;
//                                             controller.hDayTime(index);
//                                           },
//                                         ),
//                                       ),
//                                     ),
//                                   ),
//                                 ],
//                               ),
//                               Row(
//                                 children: [
//                                   Obx(
//                                     () => Visibility(
//                                       visible: controller
//                                           .dayTimeList[index].isSelect.value,
//                                       child: Flexible(
//                                         child: Row(
//                                             mainAxisSize: MainAxisSize.max,
//                                             mainAxisAlignment:
//                                                 MainAxisAlignment.end,
//                                             crossAxisAlignment:
//                                                 CrossAxisAlignment.end,
//                                             children: [
//                                               SizedBox(
//                                                 height: H * 0.04,
//                                               ),
//                                               // Container(
//                                               //   width: W * 0.2,
//                                               // ),
//                                               controller
//                                                           .dayTimeList[index]
//                                                           .secondTime
//                                                           ?.isEmpty ??
//                                                       true
//                                                   ? Row(
//                                                       children: [
//                                                         InkWell(
//                                                           onTap: () {
//                                                             controller
//                                                                 .dayTimeList[
//                                                                     index]
//                                                                 .secondTime
//                                                                 ?.add(
//                                                                     "selected");
//                                                             controller.update();
//                                                           },
//                                                           child: const Text(
//                                                             "+ Add Additional Time",
//                                                             style: TextStyle(
//                                                               color: primary,
//                                                               fontSize: 20,
//                                                               fontWeight:
//                                                                   FontWeight
//                                                                       .w700,
//                                                             ),
//                                                           ),
//                                                         ),
//                                                       ],
//                                                     )
//                                                   : Row(
//                                                       children: [
//                                                         IconButton(
//                                                           onPressed: () {
//                                                             controller
//                                                                 .dayTimeList[
//                                                                     index]
//                                                                 .secondTime
//                                                                 ?.remove(
//                                                                     "selected");
//                                                             controller.update();
//                                                           },
//                                                           icon: const Icon(
//                                                             Icons.delete,
//                                                             color: Colors.red,
//                                                             size: 20,
//                                                           ),
//                                                         ),
//                                                         Obx(
//                                                           () => Card(
//                                                             shape:
//                                                                 RoundedRectangleBorder(
//                                                               borderRadius:
//                                                                   BorderRadius
//                                                                       .circular(
//                                                                           45),
//                                                             ),
//                                                             elevation: 5,
//                                                             child: SizedBox(
//                                                               height: H * 0.04,
//                                                               width: W * 0.27,
//                                                               child:
//                                                                   DropdownButtonFormField<
//                                                                       String>(
//                                                                 validator:
//                                                                     (val) {
//                                                                   if (val !=
//                                                                           null &&
//                                                                       controller
//                                                                           .dayTimeList[
//                                                                               index]
//                                                                           .isSelect
//                                                                           .isTrue) {
//                                                                     return null;
//                                                                   }
//                                                                   return "";
//                                                                 },
//                                                                 elevation: 15,
//                                                                 decoration:
//                                                                     const InputDecoration(
//                                                                   enabled:
//                                                                       false,
//                                                                   contentPadding:
//                                                                       EdgeInsets.fromLTRB(
//                                                                           12.0,
//                                                                           2.0,
//                                                                           8.0,
//                                                                           2.0),
//                                                                   filled: true,
//                                                                   fillColor:
//                                                                       Colors
//                                                                           .white,
//                                                                   border:
//                                                                       OutlineInputBorder(
//                                                                     borderRadius:
//                                                                         BorderRadius.all(
//                                                                             Radius.circular(45)),
//                                                                   ),
//                                                                 ),
//                                                                 isExpanded:
//                                                                     true,
//                                                                 hint:
//                                                                     const Text(
//                                                                   "Select Time",
//                                                                   style: TextStyle(
//                                                                       fontSize:
//                                                                           12,
//                                                                       color: Colors
//                                                                           .grey),
//                                                                 ),
//                                                                 icon: const Icon(
//                                                                     Icons
//                                                                         .keyboard_arrow_down),
//                                                                 items: controller
//                                                                         .dayTimeList[
//                                                                             index]
//                                                                         .isSelect
//                                                                         .isTrue
//                                                                     ? controller
//                                                                         .timesList
//                                                                         .map((time) =>
//                                                                             DropdownMenuItem(
//                                                                               value: time,
//                                                                               child: Text(
//                                                                                 time,
//                                                                                 style: const TextStyle(
//                                                                                   color: Colors.black,
//                                                                                   fontSize: 14,
//                                                                                 ),
//                                                                               ),
//                                                                             ))
//                                                                         .toList()
//                                                                     : [],
//                                                                 onChanged:
//                                                                     (time) {
//                                                                   controller
//                                                                           .hFromTime2 =
//                                                                       time;
//                                                                 },
//                                                               ),
//                                                             ),
//                                                           ),
//                                                         ),
//                                                         SizedBox(
//                                                           width: W * 0.018,
//                                                         ),
//                                                         Obx(
//                                                           () => Card(
//                                                             shape:
//                                                                 RoundedRectangleBorder(
//                                                               borderRadius:
//                                                                   BorderRadius
//                                                                       .circular(
//                                                                           45),
//                                                             ),
//                                                             elevation: 5,
//                                                             child: SizedBox(
//                                                               height: H * 0.04,
//                                                               width: W * 0.28,
//                                                               child:
//                                                                   DropdownButtonFormField<
//                                                                       String>(
//                                                                 validator: controller
//                                                                         .dayTimeList[
//                                                                             index]
//                                                                         .isSelect
//                                                                         .isTrue
//                                                                     ? (value) {
//                                                                         if (value ==
//                                                                                 null ||
//                                                                             value.trim().isEmpty) {
//                                                                           return 'select';
//                                                                         }

//                                                                         return null;
//                                                                       }
//                                                                     : null,
//                                                                 elevation: 15,
//                                                                 decoration:
//                                                                     const InputDecoration(
//                                                                   enabled:
//                                                                       false,
//                                                                   contentPadding:
//                                                                       EdgeInsets.fromLTRB(
//                                                                           12.0,
//                                                                           2.0,
//                                                                           8.0,
//                                                                           2.0),
//                                                                   filled: true,
//                                                                   fillColor:
//                                                                       Colors
//                                                                           .white,
//                                                                   border:
//                                                                       OutlineInputBorder(
//                                                                     borderRadius:
//                                                                         BorderRadius.all(
//                                                                             Radius.circular(45)),
//                                                                   ),
//                                                                 ),
//                                                                 isExpanded:
//                                                                     true,
//                                                                 hint:
//                                                                     const Text(
//                                                                   "Select Time",
//                                                                   style: TextStyle(
//                                                                       fontSize:
//                                                                           12,
//                                                                       color: Colors
//                                                                           .grey),
//                                                                 ),
//                                                                 icon: const Icon(
//                                                                     Icons
//                                                                         .keyboard_arrow_down),
//                                                                 items: controller
//                                                                         .dayTimeList[
//                                                                             index]
//                                                                         .isSelect
//                                                                         .isTrue
//                                                                     ? controller
//                                                                         .timesList
//                                                                         .map((time) =>
//                                                                             DropdownMenuItem(
//                                                                               value: time,
//                                                                               child: Text(
//                                                                                 time,
//                                                                                 style: const TextStyle(
//                                                                                   color: Colors.black,
//                                                                                   fontSize: 14,
//                                                                                 ),
//                                                                               ),
//                                                                             ))
//                                                                         .toList()
//                                                                     : [],
//                                                                 onChanged:
//                                                                     (time) {
//                                                                   controller
//                                                                           .hToTime2 =
//                                                                       time;
//                                                                   controller
//                                                                       .hDayTime(
//                                                                           index);
//                                                                 },
//                                                               ),
//                                                             ),
//                                                           ),
//                                                         ),
//                                                       ],
//                                                     ),
//                                             ]),
//                                       ),
//                                     ),
//                                   ),
//                                 ],
//                               )
//                             ],
//                           ),
//                         );
//                       }),
//                   SizedBox(
//                     height: H * 0.3,
//                   ),
//                 ],
//               ),
//             ),
//           ),
//         ),
//         bottomNavigationBar: Padding(
//           padding: const EdgeInsets.only(left: 16.0, right: 16, bottom: 32),
//           child: SizedBox(
//             height: H * 0.09,
//             child: CustomElevatedButtonWidget(
//               onPressed: () {
//                 controller.onDayTimeNextTap();
//               },
//               verticalPadding: 0,
//               text: "Next",
//               textColor: blackColor,
//               fontSize: 24,
//               borderRadius: 45,
//             ),
//           ),
//         ),
//       );
//     });
//   }
// }
